layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  #   - stars_with_pushed
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  keybase: kpherox
  twitter: kpherox_dev
  stackoverflow: 8908950
  website: https://www.kr-kp.com
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # linkedin: your_username
  # medium: your_username
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  # youtube: your_username

topics:
  - name: Electron
    web_url: https://github.com/topics/electron
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/electron/electron.png

  - name: Swift
    web_url: https://github.com/topics/swift
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/swift/swift.png

  - name: Laravel
    web_url: https://github.com/topics/laravel
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/laravel/laravel.png
