layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars_with_pushed
  # sort_by options:
  #   - pushed
  #   - stars
  #   - stars_with_pushed
  limit: 9
  exclude:
    forks: true
    projects:
      - kpherox.github.io

social_media:
  keybase: kpherox
  twitter: kpherox_dev
  stackoverflow: 8908950
  website: https://www.kr-kp.com
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # linkedin: your_username
  # medium: your_username
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  # youtube: your_username

interests:
  explore_hash: 80688e429a7d4ef2fca1e82350fe8e3517d3494d
  topics:
    - name: Electron
      tag: electron
      has_image: true

    - name: Vue.js
      tag: vue
      has_image: true

    - name: Go
      tag: go
      has_image: true

    - name: Swift
      tag: swift
      has_image: true

    - name: TypeScript
      tag: typescript
      has_image: true

    - name: Laravel
      tag: laravel
      has_image: true
